site: Index Jekyll Theme

url: https://index.jekyllthemes.io
baseurl: 

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /blog/:slug
  projects:
    output: true
    permalink: /project/:slug
  products:
    output: true
    permalink: /product/:name
  categories:
    output: true
    permalink: /categories/:slug
  subcategories:
    output: true
    permalink: /subcategories/:slug
  partners:
    output: true
    permalink: /partners/:slug

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "projects"
    values:
      layout: "project"

  -
    scope:
      path: ""
      type: "products"
    values:
      layout: "product"
  -
    scope:
      path: ""
      type: "categories"
    values:
      layout: "category"
  -
    scope:
      path: ""
      type: "subcategories"
    values:
      layout: "subcategory"

  -
    scope:
    path: ""
    type: "partners"
    values:
    layout: "partners"

markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  
sass:
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll-sitemap

paginate: 6
paginate_path: "/blog/page:num/"
  